### ISSUE TITLE
Test for subtasks

### ISSUE THREAD

**Issue by JingsongLi** [ververica/flink-cdc-connectors#2022]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Motivation

test subtasks with template

### Anything else?

Task List:
- [] first sub task.
- [] second sub task.
- [] third sub task.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!
